services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgres://postgres:1234@db:5432/app_db?sslmode=disable
      - JWT_SECRET=your_strong_jwt_secret_here
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: